manuals: fix quoting of double dashes
Otherwise rendered as "en" dashes by sphinx, for example:
git pull –rebase
instead of
git pull --rebase

Readers could confuse them with normal dashes.

Exception: replace by \-\- in italic text (*text*)
as Sphinx cannot nest italic and quoted text.

For consistency, also update quoting in strings in the same code hunks.

Signed-off-by: Michael Opdenacker <michael.opdenacker@bootlin.com>